"""Added birthdate column to User

Revision ID: 7f345c556296
Revises: 
Create Date: 2024-12-15 16:50:52.994314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f345c556296'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mytask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=100), nullable=False))
        batch_op.drop_column('Content')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('content', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('complete', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.drop_column('password')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_column('created')
        batch_op.drop_column('complete')
        batch_op.drop_column('priority')
        batch_op.drop_column('content')
        batch_op.drop_column('title')

    with op.batch_alter_table('mytask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Content', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
